version: "3"
services:
  bot:
    build:
      context: .
      args:
        - service_src=./bot/src
    command: bash -c "npm run start:dev"
    restart: on-failure
    env_file:
      - ./bot/environment
    volumes:
      - ./bot/src:/usr/src/app/service/src:cached
      - ./common:/usr/src/app/common:cached
mongo:
  image: "mongo:latest"
  ports:
    - 27017:27017
rabbitmq:
  image: "rabbitmq:management"
  ports:
    - "5672:5672"
    - "15672:15672"
