version: "3"
services:
  backend:
    container_name: home_assignment
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: "mongo:latest"
    ports:
      - 27017:27017
    volumes:
      - ./docker-init-mongo.js:/docker-entrypoint-initdb.d/docker-init-mongo.js
    environment:
      MONGO_INITDB_DATABASE: home-assignment
  # rabbitmq:
  #   container_name: rabbitmq
  #   image: "rabbitmq:management"
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
